apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: auth-servicemonitor
  namespace: monitoring
  labels:
    release: monitoring
spec:
  namespaceSelector:
    any: true
  selector:
    matchLabels:
      app: auth
  endpoints:
    - port: http
      path: /metrics
      interval: 15s
