apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: auth-servicemonitor
  namespace: monitoring
  labels:
    release: monitoring        
spec:
  namespaceSelector:
    matchNames:
      - default                
  selector:
    matchLabels:
      app: auth
  endpoints:
    - port: http
      path: /metrics
      interval: 15s
