apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: auth-servicemonitor
  namespace: monitoring
  labels:
    release: monitoring        # 👈 must match Prometheus Helm release name
spec:
  namespaceSelector:
    matchNames:
      - default                # 👈 scrape Services from the default namespace
  selector:
    matchLabels:
      app: auth
  endpoints:
    - port: http
      path: /metrics
      interval: 15s
