apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth
  namespace: default
  labels:
    app: auth
spec:
  replicas: 2
  selector:
    matchLabels:
      app: auth
  template:
    metadata:
      labels:
        app: auth
    spec:
      containers:
        - name: auth
          image: edison45/auth-service:v6
          ports:
            - name: http
              containerPort: 3000
          env:
            - name: MONGO_URI
              value: "mongodb://mongo:27017"
