apiVersion: v1
kind: Service
metadata:
  name: auth
  labels:
    app: auth
spec:
  selector:
    app: auth
  ports:
    - name: http           # ← important
      port: 3000
      targetPort: 3000
  type: ClusterIP
