apiVersion: v1
kind: Service
metadata:
  name: auth
  namespace: default
  labels:
    app: auth
spec:
  selector:
    app: auth
  ports:
    - name: http               
      port: 3000
      targetPort: 3000
  type: ClusterIP
