apiVersion: v1
kind: Service
metadata:
  name: tasks
  labels:
    app: tasks
spec:
  selector:
    app: tasks
  ports:
    - name: http           
      port: 5000
      targetPort: 5000
  type: ClusterIP


apiVersion: v1
kind: Service
metadata:
  name: tasks-loadbalancer
spec:
  selector:
    app: tasks
  ports:
    - name: http         
      protocol: TCP
      port: 80
      targetPort: 5000
  type: LoadBalancer
